### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by PedroKim** [ronnydeng67/TechGurus#1]
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

## Comments
- Please update your welcome message.
- I highly advise you to come up with an actual name for your project as it will be difficult to change it later.
- Include placeholder of where the live link will live.

**Comment by ronnydeng67** [comment]
Hi Peter, thanks for the advice, I fixed the issues.
